name: ${name}
version: ${version}
main: ${main}
api-version: ${apiVersion}
folia-supported: true
website: VolmitSoftware.com
commands:
  biletools:
    aliases: [bile, bi, b, volmit, vomit, vom]
permissions:
  bile.use:
    description: Gives access to biletools
    default: op
