[versions]
# Plugins
lombok = "9.2.0"
shadow = "9.0.0-rc3"
runTask = "2.3.1"

# Libraries
paper = "26.2.build.60-beta"
bstats = "3.2.1"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runTask" }
